### ISSUE TITLE
.tmx files for the different level tile maps are missing

### ISSUE THREAD

**Issue by AmirAsaraf** [bneukom/heavydefense#5]
`	this.levels = new Level[] {
				new SnowLevel("Snow", "levels/snow.tmx", new SnowBackground(stageCamera), Difficulty.EASY),
				new WoodsLevel("Woods", "levels/woods.tmx", new WoodsBackground(stageCamera), Difficulty.EASY),
				new DesertLevel("Desert", "levels/desert.tmx", new DesertBackground(stageCamera), Difficulty.MEDIUM),
				new BeachLevel("Beach", "levels/beach.tmx", new BeachBackground(stageCamera), Difficulty.MEDIUM),
				new GrassLevel("Grass", "levels/grass.tmx", new GrassBackground(stageCamera), Difficulty.MEDIUM),
				new LavalLevel("Lava", "levels/lava.tmx", new LavaBackground(stageCamera), Difficulty.HARD),
				new VulcanoLevel("Vulcano", "levels/vulcano.tmx", new VulcanoBackground(stageCamera), Difficulty.HARD),`

**Comment by bneukom** [comment]
Added other missing assets with commit 24c7f4cd32a1995bd23a13b21d390c935ed696e4 (maps, UI graphics etc.)
